services:
    website:
        image: ghcr.io/jesseogunlaja/whispr:latest
        environment:
            - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
            - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
            - STREAMTHING_SERVER_PASSWORD=${STREAMTHING_SERVER_PASSWORD}
        ports:
            - "80:3000"
        depends_on:
            - postgres

    postgres:
        build:
            context: .
            dockerfile: Dockerfile.postgres
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        volumes:
            - postgres-data:/var/lib/postgresql/

volumes:
    postgres-data:
